export const client = {
  name: "Haydon Hill Paving Ltd",
  tagline: "Professional Paving in Aylesbury — Quality You Can Trust",
  description: "Professional paving services in Aylesbury and surrounding areas. Trusted local experts with 14 Google reviews.",
  category: "Paving",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Aylesbury",
  county: "",
  postcode: "",
  basedIn: "Aylesbury",
  founderName: "",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.4",
  reviewCount: "14",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Ian Wilkinson", rating: 5, text: "Cannot recommend Hayden Hill highly enough. We had major work done to our back garden and a complete new block paved drive and not one single problem from start to finish. From the time Warren first came out to completion, communications have been absolutely excellent and I have never come across a group of workers that have worked so hard, been so meticulous with every aspect of the job in hand, so tidy and just thoroughly pleasant. An absolute pleasure to have all of them working here.", date: "a year ago" },
    { name: "Jamie Gibson", rating: 5, text: "Warren and his team were quick, professional and hard working in not great weather to make sure the job was done. Helpful and attentive throughout - would definitely recommend", date: "2 years ago" },
    { name: "Colin Wreglesworth", rating: 5, text: "Great service. Job executed efficiently and on time. Would use again", date: "2 years ago", badge: "Local Guide" },
    { name: "Mark Taylor", rating: 5, text: "Just had a drive and patio layed, very professional and a great job ,would highly recommend this company.", date: "2 years ago" },
    { name: "Faizaan Mahmood", rating: 5, text: "Big thanks to Waz and his team, completely transformed my garden very professional always on time and got the job done.  Prices are very fair and the service couldn’t be any better the best in town and Bedgroves favourite!  Will highly recommend", date: "2 years ago" },
    { name: "John Considine", rating: 5, text: "Warren and his great team is lads did a superb job on installing a new driveway and extending a current parking area, top marks, couldn't be more pleased with the fantastic job you've done. Don't use anyone else,  I HIGHLY RECOMMEND.", date: "2 years ago", badge: "Local Guide" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Haydon Hill Paving Ltd | Professional Paving in Aylesbury",
    description: "Professional paving in Aylesbury. 4.4 stars on Google with 14 reviews. Quality workmanship guaranteed.",
  },
};
